| Product Name                   | 説明                                                                                             | ポイント                                                                                                                                                        |
| ------------------------------ | ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Compute Engine                 | Scalable, high performance VMs.                                                                | OSレベルのチューニング、第３者のアプリをインストールして使わなければならないケース                                                                                                                  |
| App Engine                     | PaaS for apps and backends.                                                                    | 一番歴史があるPaaS製品、古くから使っている                                                                                                                                     |
| Kubernetes Engine              | Run containerized applications.                                                                | コンテーナーエンジン、KubernetesをGoogle Cloud上で運用したい場合に使う。最近ノードの管理が必要ないAutopolitモードができた                                                                                |
| Cloud Functions                | Event-driven serverless compute platform.                                                      | Pub/Sub連携やEvent-drivenで動かすとき使う                                                                                                                              |
| Cloud SQL                      | MySQL and PostgreSQL database service.                                                         | MySQL, MSSQL, PostgreSQLを使える。                                                                                                                               |
| Cloud Bigtable                 | NoSQL wide-column database service.                                                            | Iotセンサー等からくる膨大なRequestを捌ける。Pub/Subと連携した使うことが多い。書き込みにすごく強い                                                                                                   |
| Cloud Spanner                  | Mission-critical, scalable, relational database service.                                       | New SQLの種類で、全世界に対象にトランジャークションを守必要がある時。RDBである。強い一貫性を持つ。Responseが早い                                                                                           |
| Cloud Datastore                | NoSQL document database service.                                                               | NoSQL ドキュメント データベース、最近は FirebaseのDatastoreモードで使われる                                                                                                          |
| Monitoring                     | Monitoring for applications on GCP and AWS.                                                    | GCPもモニタリング。アラートとかを飛ばせる                                                                                                                                      |
| Logging                        | Logging for applications on GCP and AWS.                                                       | GCPのログ管理。ログの確認検索ができる。Monitoringと連携                                                                                                                          |
| Trace                          | Find performance bottlenecks in production.                                                    | アプリ間でエラーが発生した時にアプリ、Networkをまたがって追跡ができる                                                                                                                      |
| Debugger                       | Investigate code behavior in production.                                                       | アプリのバグを探す時に使う                                                                                                                                               |
| Cloud Console                  | GCP’s integrated management console.                                                           | UIでGoogle Cloudをマネジメントするコンソール                                                                                                                               |
| Cloud Shell                    | Command-line management from any browser.                                                      | Cloud Consoleから実行できる、ユーザー別に生成される小さいVMで無償で使える。簡単な作業をここで行う                                                                                                    |
| Apigee API Platform            | Develop, secure, deploy, and monitor your APIs everywhere.                                     | API Gateway 複数のAPIを管理したり、制限をかけたり、割り当てが自由にできるサービス                                                                                                            |
| Cloud Storage                  | Object storage with global edge-caching.                                                       | Google Cloudのストレじサービス、４つのClassがある、Stand: よく使うファイル、NearLine: 四半期に１回ぐらいに使うファイル、Cold line: 半年に１回ぐらい使うファイル、Archive: 年１回もつかわないファイル。　Stand -> Archiveに行くほど値段が安くなる |
| Cloud Memorystore              | Fully managed in-memory data store service.                                                    | すごく早いスピードでResponseを返す。                                                                                                                                      |
| Cloud Firestore                | NoSQL document database service with syncing for mobile apps                                   | モバイルAppのデータベースとしてよく使われる. Off-line Sync機能(Fire Store)がある。                                                                                                    |
| Cloud Filestore                | Store and serve content with ease.                                                             | NASのようにファイルを保存するサービス                                                                                                                                        |
| Virtual Private Cloud (VPC)    | VPC networking for GCP resources.                                                              | 仮想ネットワーク、複数のリージョンに渡って作成ができる。１Projectに複数生成可能                                                                                                                 |
| Cloud Load Balancing           | High-performance, scalable load balancing.                                                     | 外部から来るRequestを後ろのサービスにバランシングしてくれる。Cloud Armorと連携してDDos攻撃とかWAF保護をする                                                                                          |
| Cloud Armor                    | Protect your services against DoS and web attacks                                              | セキュリティー サービスでDDos等の攻撃から守                                                                                                                                    |
| Cloud CDN                      | Content delivery on Google's global network.                                                   | コンテンツを早くユーザー送るサービス（画像とかHTMLとか）                                                                                                                              |
| Cloud Interconnect             | Connect directly to GCP’s network edge.                                                        | On-prem環境や他者クラウド環境とGCPを繋ぐ時にInternetを経由せず、直接繋ぐ時に使う                                                                                                           |
| Cloud SDK                      | CLI for GCP products and services.                                                             | コマンドラインでGCPを制御する時にインストールするツール                                                                                                                               |
| Container Registry             | Fast, private image storage.                                                                   | GKEとかCloud Runで使うコンテナーイメージを保管するサービス                                                                                                                         |
| BigQuery                       | Fully managed cloud data warehouse.                                                            | 高速のDWHサービス。低コストで大量のデータの分析が可能                                                                                                                                |
| Cloud Dataflow                 | Real-time batch and stream data processing.                                                    | オープンソースの Apache Beamのベース、StreamデータもBatchデータも処理可能で、Bigqueryにデータを入れる時によく使う                                                                                    |
| Cloud Dataproc                 | Managed Spark and Hadoop service.                                                              | オープンソースの Apache Sparkのベースで　Hadoopサービスのマネージドー                                                                                                                |
| Cloud Dataprep                 | Explore, clean, and prepare data for analysis.                                                 | サーバーレス、分析、レポート、機械学習に使用する構造化データと非構造化データを視覚的に探索、クリーニング、準備できるインテリジェント データ サービス                                                                                 |
| Cloud Pub/Sub                  | Ingest event streams from anywhere, at any scale.                                              | 非同期のスケーラブルなメッセージング サービス。IoTシステムでよく使える。あらゆるシステム間の連携で使える                                                                                                      |
| Google Looker Studio           | Tell great data stories to support better business decisions Compare to QuickSite or Power BI. | Free BI tool                                                                                                                                                |
| Cloud AutoML                   | Machine learning made easy.                                                                    | 機械学習の専門知識が限られていても、ビジネスニーズに合った高品質のモデルをトレーニング                                                                                                                 |
| Cloud TPU                      | Train and run ML models faster than ever.                                                      | Tensor Processing Unit. ML(機械学習)のためにGoogleが作ったHardware                                                                                                      |
| Cloud Natural Language         | Derive insights from unstructured text.                                                        | 自然言語処理。機械学習を使用して非構造化テキストから分析情報を引き出す                                                                                                                         |
| Cloud Speech-to-Text           | Speech-to-text conversion powered by ML.                                                       | 音声文字変換                                                                                                                                                      |
| Cloud Text-to-Speech           | Text-to-speech conversion powered by ML.                                                       | 文字音声変換                                                                                                                                                      |
| Cloud Vision API               | Derive insight from images powered by ML.                                                      | 画像や動画からの分析情報                                                                                                                                                |
| Cloud IAM                      | Fine-grained identity and access management.                                                   | Identity and Access Management（IAM）を使用すると、特定のリソースに対するアクションの実行を、承認を受けたユーザーのみに許可                                                                              |
| Cloud Identity-Aware Proxy     | Use identity to guard access.                                                                  | ID とコンテキストを使用して、アプリケーションや VM へのアクセスを保護。                                                                                                                     |
| Cloud Data Loss Prevention API | Discover and redact sensitive data.                                                            | テキスト、画像、Google Cloud Platform ストレージ リポジトリ内のプライバシーに敏感なフラグメントを検出する方法を提供。                                                                                      |
| Cloud Key Management Service   | Manage encryption keys on GCP.                                                                 | 一元化された高速かつスケーラブルなクラウド鍵管理                                                                                                                                    |
| Resource Manager               | Hierarchically manage resources on GCP.                                                        | プロジェクト、フォルダ、組織ごとに、階層的にリソースを管理                                                                                                                               |
| Cloud Security Command Center  | Comprehensive security and data risk platform for GCP.                                         | 構成ミスと脆弱性の特定、サイバーリスクの特定と修復の優先順位付け、Google Cloud リソースを標的とする脅威を検出。規制遵守のモニタリングと管理                                                                                |
